# Generated by Django 5.1.5 on 2025-02-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_alter_times_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='times',
            name='datetime',
        ),
    ]
