# Generated by Django 5.1.5 on 2025-02-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_managers_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='times',
            options={'verbose_name_plural': 'Times'},
        ),
        migrations.AlterModelOptions(
            name='todos',
            options={'verbose_name_plural': 'Todos'},
        ),
    ]
