# Generated by Django 5.1.5 on 2025-02-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_todos_tasks_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
