# Generated by Django 5.1.5 on 2025-02-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_tasks'),
        ('user', '0005_delete_times'),
    ]

    operations = [
    ]
