# Generated by Django 5.1.5 on 2025-02-22 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_merge_0005_delete_tasks_0005_delete_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='default_time',
        ),
        migrations.AddField(
            model_name='customuser',
            name='break_time',
            field=models.DurationField(default=datetime.timedelta(seconds=300)),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_pomodoro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='work_time',
            field=models.DurationField(default=datetime.timedelta(seconds=1500)),
        ),
    ]
